config/routes.rb
Rails.application.routes.draw do
  root 'languages#index'
  resources :languages
  post '/translate' => 'languages#translate'

end

app/models/input.rb
class Input < ActiveRecord::Base
end

app/models/language.rb
class Language < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/languages_controller.rb
require 'net/http'
require 'byebug'
class LanguagesController < ApplicationController
  # GET /languages
  # GET /languages.json
  def index
    if Language.count == 0
      url = URI.parse("https://www.googleapis.com/language/translate/v2/languages?target=en&key=#{ENV["KEY"]}")
      req = Net::HTTP::Get.new(url.request_uri)
      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = (url.scheme == "https")
      response = http.request(req)
      response = (JSON.parse(response.body)).deep_symbolize_keys
      response = response[:data]
      response = response[:languages]
      response.each do |language|
        Language.create(language: language[:language], name: language[:name])
      end
    end
    @languages = Language.all
  end

  def translate
    input = params["input"]
    input = input.tr(" ", "+")
    language = params["language"]
    language1 = language["language1"]
    language2 = language["language2"]
    url = URI.parse("https://www.googleapis.com/language/translate/v2?q=#{input}&target=#{language2}&source=#{language1}&key=#{ENV["KEY"]}")
    req = Net::HTTP::Get.new(url.request_uri)
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = (url.scheme == "https")
    response = http.request(req)
    response = (JSON.parse(response.body)).deep_symbolize_keys
    response = response[:data][:translations]
    @output = response[0][:translatedText]
    @languages = Language.all
    render action: 'index'
  end


  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def language_params
      params.require(:language).permit(:language, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/languages/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Translator</h1>
<table>
  <thead>
    <tr>
      <td>Input Language</td>
      <td></td>
      <td>Output Language</td>
    </tr>
  </thead>
  <tbody>
    <%= form_tag({controller: "languages", action: "translate"}, method: "post") do %>
    <tr>
      <td><%= collection_select(:language, :language1, @languages, :language, :name) %></td>
      <td align="center">to:</td>
      <td><%= collection_select(:language, :language2, @languages, :language, :name) %></td>
    </tr>
    <tr></tr>
    <tr>
      <td><%= text_field_tag :input, params[:input] %></td>
      <td><%= submit_tag ("Translate") %></td>
      <td align="center"><%= @output %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/languages/new.html.erb
<h1>New Language</h1>

<%= render 'form' %>

<%= link_to 'Back', languages_path %>

app/views/languages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Language:</strong>
  <%= @language.language %>
</p>

<p>
  <strong>Name:</strong>
  <%= @language.name %>
</p>

<%= link_to 'Edit', edit_language_path(@language) %> |
<%= link_to 'Back', languages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Translator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>